language: python
python:
  - "3.5.3"
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements.txt codecov
script:
  - coverage run manage.py test
  - coverage report
after_success:
  - codecov

