# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='id',
            new_name='uuid_pk',
        ),
    ]
